import fs from 'fs';
import path from 'path';

/**
 * Extracts a UTC millisecond timestamp from an evidence run folder name
 * (which follows format: YYYYMMDDTHHMMSS_... as generated by EvidenceRecorder)
 * or falls back to filesystem mtime.
 */
export function parseRunTimestamp(folderName, folderPath) {
  const match = String(folderName).match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})/);
  if (match) {
    const [, y, m, d, hh, mm, ss] = match;
    const dt = new Date(Date.UTC(+y, +m - 1, +d, +hh, +mm, +ss));
    if (!isNaN(dt.getTime())) {
      return dt.getTime();
    }
  }

  if (folderPath && fs.existsSync(folderPath)) {
    try {
      const stat = fs.statSync(folderPath);
      return stat.mtimeMs;
    } catch (_) {
      return null;
    }
  }

  return null;
}

/**
 * Recursively calculates the disk space occupied by a directory in bytes.
 */
export function calculateDirectorySizeBytes(dirPath) {
  if (!fs.existsSync(dirPath)) return 0;
  let totalBytes = 0;

  try {
    const entries = fs.readdirSync(dirPath, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dirPath, entry.name);
      if (entry.isDirectory()) {
        totalBytes += calculateDirectorySizeBytes(fullPath);
      } else if (entry.isFile()) {
        try {
          const stat = fs.statSync(fullPath);
          totalBytes += stat.size;
        } catch (_) {}
      }
    }
  } catch (_) {}

  return totalBytes;
}

/**
 * Formats bytes into a human-readable string (KiB, MiB, GiB).
 */
export function formatBytes(bytes) {
  if (typeof bytes !== 'number' || isNaN(bytes) || bytes <= 0) {
    return '0 B';
  }
  const units = ['B', 'KiB', 'MiB', 'GiB', 'TiB'];
  const exponent = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
  const value = bytes / Math.pow(1024, exponent);
  return `${value.toFixed(1)} ${units[exponent]}`;
}

/**
 * Clean evidence folders for a single profile.
 * Only evidence folders older than `daysThreshold` days are deleted.
 * All evidence created within `daysThreshold` is strictly kept.
 *
 * @param {string} profileDir - Absolute path to the profile directory
 * @param {number} daysThreshold - Number of days of evidence to keep (default: 3)
 * @param {number} nowMs - Optional current timestamp in ms (for testing)
 * @returns {object} Cleanup metrics
 */
export function cleanProfileEvidence(profileDir, daysThreshold = 3, nowMs = Date.now()) {
  const evidenceDir = path.join(profileDir, 'automation_evidence');
  if (!fs.existsSync(evidenceDir)) {
    return {
      deleted_runs: 0,
      freed_bytes: 0,
      freed_mb: 0,
      freed_formatted: '0 B',
      kept_runs: 0,
    };
  }

  const cutoffMs = nowMs - daysThreshold * 24 * 60 * 60 * 1000;
  let deletedRuns = 0;
  let freedBytes = 0;
  let keptRuns = 0;

  try {
    const entries = fs.readdirSync(evidenceDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;

      const runDir = path.join(evidenceDir, entry.name);
      const timestamp = parseRunTimestamp(entry.name, runDir);

      // If we cannot determine a timestamp, do not delete it to be safe
      if (timestamp === null) {
        keptRuns += 1;
        continue;
      }

      if (timestamp < cutoffMs) {
        const dirSize = calculateDirectorySizeBytes(runDir);
        try {
          fs.rmSync(runDir, { recursive: true, force: true });
          deletedRuns += 1;
          freedBytes += dirSize;
        } catch (rmErr) {
          console.error(`Failed to remove old evidence directory ${runDir}:`, rmErr);
          keptRuns += 1;
        }
      } else {
        keptRuns += 1;
      }
    }
  } catch (err) {
    console.error(`Failed to read evidence directory ${evidenceDir}:`, err);
  }

  return {
    deleted_runs: deletedRuns,
    freed_bytes: freedBytes,
    freed_mb: +(freedBytes / (1024 * 1024)).toFixed(2),
    freed_formatted: formatBytes(freedBytes),
    kept_runs: keptRuns,
  };
}

/**
 * Clean evidence folders across all profiles in the profiles directory.
 *
 * @param {string} profilesDir - Absolute path to the profiles directory
 * @param {number} daysThreshold - Number of days of evidence to keep (default: 3)
 * @param {number} nowMs - Optional current timestamp in ms (for testing)
 * @returns {object} Aggregated cleanup metrics
 */
export function cleanAllProfilesEvidence(profilesDir, daysThreshold = 3, nowMs = Date.now()) {
  if (!fs.existsSync(profilesDir)) {
    return {
      total_deleted_runs: 0,
      total_freed_bytes: 0,
      total_freed_mb: 0,
      total_freed_formatted: '0 B',
      total_kept_runs: 0,
      profiles: {},
    };
  }

  let totalDeleted = 0;
  let totalFreed = 0;
  let totalKept = 0;
  const profileResults = {};

  try {
    const entries = fs.readdirSync(profilesDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory() || entry.name === 'shared_media') continue;

      const profilePath = path.join(profilesDir, entry.name);
      const result = cleanProfileEvidence(profilePath, daysThreshold, nowMs);
      profileResults[entry.name] = result;
      totalDeleted += result.deleted_runs;
      totalFreed += result.freed_bytes;
      totalKept += result.kept_runs;
    }
  } catch (err) {
    console.error(`Failed to scan profiles dir ${profilesDir}:`, err);
  }

  return {
    total_deleted_runs: totalDeleted,
    total_freed_bytes: totalFreed,
    total_freed_mb: +(totalFreed / (1024 * 1024)).toFixed(2),
    total_freed_formatted: formatBytes(totalFreed),
    total_kept_runs: totalKept,
    profiles: profileResults,
  };
}
